---
- name: Gather package facts
  package_facts:
    manager: auto

- name: Install Google Chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    update_cache: true
  become: true
  when: "'google-chrome-stable' not in ansible_facts.packages"
