---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

# TODO Migrate to APT repository, when available
- name: Install bat
  ansible.builtin.apt:
    deb: "https://github.com/sharkdp/bat/releases/download/v{{ bat_version }}/bat_{{ bat_version }}_arm64.deb"
    update_cache: true
  become: true
  when: "'bat' not in ansible_facts.packages"
  vars:
    bat_version: "0.18.0"
