name: Molecule Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    working-directory: egvimo.installer

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ANSIBLE_FORCE_COLOR: 1

    steps:
      - uses: actions/checkout@v2
        with:
          path: egvimo.installer

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run molecule tests
        run: molecule test

      - name: Import role to Galaxy
        if: github.ref == 'refs/heads/main'
        run: ansible-galaxy role import --api-key ${{ secrets.ANSIBLE_GALAXY_API_KEY }} $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
