---
- name: Install Visual Studio Code
  ansible.windows.win_package:
    path: https://go.microsoft.com/fwlink/?LinkID=534107
    arguments: /VERYSILENT /NORESTART /MERGETASKS=!runcode
    #creates_path: C:\users\{username}\AppData\Local\Programs\Microsoft VS Code
    state: present
